version: '3.7'

networks:
  erxes:
    external: true

services:
  coreui:
    image: erxes/erxes-next-ui:latest
    environment:
      REACT_APP_PUBLIC_PATH: ''
      REACT_APP_CDN_HOST: https://test.erxes.io/widgets
      REACT_APP_API_URL: https://test.erxes.io/gateway
      REACT_APP_DASHBOARD_URL: https://test.erxes.io/dashboard/api
      REACT_APP_API_SUBSCRIPTION_URL: wss://test.erxes.io/gateway/graphql
      NGINX_PORT: 80
      NGINX_HOST: test.erxes.io
      NODE_ENV: production
      REACT_APP_FILE_UPLOAD_MAX_SIZE: 524288000
      REACT_APP_RELEASE: master
    ports:
      - 3000:80
    networks:
      - erxes
    deploy: &default_deploy
      mode: replicated
      replicas: 2
      update_config:
        order: start-first
        failure_action: rollback
        delay: 1s

  plugin-core-api:
    image: erxes/erxes-next-core-api:latest
    environment:
      OTEL_SERVICE_NAME: plugin-core-api
      SERVICE_NAME: core-api
      PORT: 80
      CLIENT_PORTAL_DOMAINS: http://localhost:8080,http://localhost:7002,http://192.168.43.156:7002/
      JWT_TOKEN_SECRET: e0f3e51e3b0e026feb8eb53ba79d876f
      LOAD_BALANCER_ADDRESS: http://plugin-core-api
      MONGO_URL: mongodb://erxes:UqKzqMhOOzFdNQhAzecLAiSk@erxes-dbs_mongo:27017/erxes?authSource=admin&replicaSet=rs0
      NODE_INSPECTOR: null
      EMAIL_VERIFIER_ENDPOINT: https://email-verifier.erxes.io
      ELASTIC_APM_HOST_NAME: null
      DEBUG: '*error*'
      NODE_ENV: production
      DOMAIN: https://test.erxes.io
      WIDGETS_DOMAIN: https://test.erxes.io/widgets
      REDIS_HOST: erxes-dbs_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_pass
      RABBITMQ_HOST: amqp://erxes:fAXkiGHctXpPHRyfOOjSxcaA@erxes-dbs_rabbitmq:5672/
      RELEASE: master
      VERSION: os
      MESSAGE_BROKER_PREFIX: ''
      ENABLED_PLUGINS: 'automations,logs,notifications,frontline,accounting,sales,content,operation'
    extra_hosts: &default_hosts []
    volumes:
      - ./permissions.json:/erxes/packages/core/permissions.json
      - ./core-api-uploads:/erxes/packages/core/src/private/uploads
    networks:
      - erxes
    deploy: *default_deploy

  service-automations:
    image: erxes/erxes-next-automations:latest
    environment:
      OTEL_SERVICE_NAME: automations
      SERVICE_NAME: automations
      PORT: 80
      CLIENT_PORTAL_DOMAINS: http://localhost:8080,http://localhost:7002,http://192.168.43.156:7002/
      JWT_TOKEN_SECRET: e0f3e51e3b0e026feb8eb53ba79d876f
      LOAD_BALANCER_ADDRESS: http://plugin-automations-api
      MONGO_URL: mongodb://erxes:UqKzqMhOOzFdNQhAzecLAiSk@erxes-dbs_mongo:27017/erxes?authSource=admin&replicaSet=rs0
      NODE_INSPECTOR: null
      ELASTIC_APM_HOST_NAME: null
      DEBUG: '*error*'
      NODE_ENV: production
      DOMAIN: https://test.erxes.io
      WIDGETS_DOMAIN: https://test.erxes.io/widgets
      REDIS_HOST: erxes-dbs_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_pass
      RELEASE: master
      VERSION: os
      MESSAGE_BROKER_PREFIX: ''
    extra_hosts: *default_hosts
    networks:
      - erxes
    deploy: *default_deploy

  service-logs:
    image: erxes/erxes-next-logs:latest
    environment:
      OTEL_SERVICE_NAME: logs-service
      SERVICE_NAME: logs-service
      PORT: 80
      CLIENT_PORTAL_DOMAINS: http://localhost:8080,http://localhost:7002,http://192.168.43.156:7002/
      JWT_TOKEN_SECRET: e0f3e51e3b0e026feb8eb53ba79d876f
      LOAD_BALANCER_ADDRESS: http://plugin-logs-api
      MONGO_URL: mongodb://erxes:UqKzqMhOOzFdNQhAzecLAiSk@erxes-dbs_mongo:27017/erxes?authSource=admin&replicaSet=rs0
      NODE_INSPECTOR: null
      ELASTIC_APM_HOST_NAME: null
      DEBUG: '*error*'
      NODE_ENV: production
      DOMAIN: https://test.erxes.io
      WIDGETS_DOMAIN: https://test.erxes.io/widgets
      REDIS_HOST: erxes-dbs_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_pass
      RELEASE: master
      VERSION: os
      MESSAGE_BROKER_PREFIX: ''
    extra_hosts: *default_hosts
    networks:
      - erxes
    deploy: *default_deploy
  service-notifications:
    image: erxes/erxes-next-notifications:latest
    environment:
      OTEL_SERVICE_NAME: notifications-service
      SERVICE_NAME: notifications-service
      PORT: 80
      CLIENT_PORTAL_DOMAINS: http://localhost:8080,http://localhost:7002,http://192.168.43.156:7002/
      JWT_TOKEN_SECRET: e0f3e51e3b0e026feb8eb53ba79d876f
      LOAD_BALANCER_ADDRESS: http://plugin-notifications-api
      MONGO_URL: mongodb://erxes:UqKzqMhOOzFdNQhAzecLAiSk@erxes-dbs_mongo:27017/erxes?authSource=admin&replicaSet=rs0
      NODE_INSPECTOR: null
      ELASTIC_APM_HOST_NAME: null
      DEBUG: '*error*'
      NODE_ENV: production
      DOMAIN: https://test.erxes.io
      WIDGETS_DOMAIN: https://test.erxes.io/widgets
      REDIS_HOST: erxes-dbs_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_pass
      RELEASE: master
      VERSION: os
      MESSAGE_BROKER_PREFIX: ''
    extra_hosts: *default_hosts
    networks:
      - erxes
    deploy: *default_deploy

  plugin-frontline-api:
    image: erxes/erxes-next-frontline_api:latest
    environment:
      OTEL_SERVICE_NAME: frontline
      SERVICE_NAME: frontline
      PORT: 80
      CLIENT_PORTAL_DOMAINS: http://localhost:8080,http://localhost:7002,http://192.168.43.156:7002/
      JWT_TOKEN_SECRET: e0f3e51e3b0e026feb8eb53ba79d876f
      LOAD_BALANCER_ADDRESS: http://plugin-frontline-api
      MONGO_URL: mongodb://erxes:UqKzqMhOOzFdNQhAzecLAiSk@erxes-dbs_mongo:27017/erxes?authSource=admin&replicaSet=rs0
      NODE_INSPECTOR: null
      ELASTIC_APM_HOST_NAME: null
      DEBUG: '*error*'
      NODE_ENV: production
      DOMAIN: https://test.erxes.io
      ENDPOINT_URL: https://enterprise.erxes.io
      WIDGETS_DOMAIN: https://test.erxes.io/widgets
      REDIS_HOST: erxes-dbs_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_pass
      ELASTICSEARCH_URL: http://erxes-dbs_elasticsearch:9200
      RELEASE: master
      VERSION: os
    extra_hosts: *default_hosts
    networks:
      - erxes
    deploy: *default_deploy

  plugin-accounting-api:
    image: erxes/erxes-next-accounting_api:latest
    environment:
      OTEL_SERVICE_NAME: accounting
      SERVICE_NAME: accounting
      PORT: 80
      CLIENT_PORTAL_DOMAINS: http://localhost:8080,http://localhost:7002,http://192.168.43.156:7002/
      JWT_TOKEN_SECRET: e0f3e51e3b0e026feb8eb53ba79d876f
      LOAD_BALANCER_ADDRESS: http://plugin-accounting-api
      MONGO_URL: mongodb://erxes:UqKzqMhOOzFdNQhAzecLAiSk@erxes-dbs_mongo:27017/erxes?authSource=admin&replicaSet=rs0
      NODE_INSPECTOR: null
      ELASTIC_APM_HOST_NAME: null
      DEBUG: '*error*'
      NODE_ENV: production
      DOMAIN: https://test.erxes.io
      WIDGETS_DOMAIN: https://test.erxes.io/widgets
      REDIS_HOST: erxes-dbs_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_pass
      ELASTICSEARCH_URL: http://erxes-dbs_elasticsearch:9200
      RELEASE: master
      VERSION: os
    extra_hosts: *default_hosts
    networks:
      - erxes
    deploy: *default_deploy

  plugin-sales-api:
    image: erxes/erxes-next-sales_api:latest
    environment:
      OTEL_SERVICE_NAME: sales
      SERVICE_NAME: sales
      PORT: 80
      CLIENT_PORTAL_DOMAINS: http://localhost:8080,http://localhost:7002,http://192.168.43.156:7002/
      JWT_TOKEN_SECRET: e0f3e51e3b0e026feb8eb53ba79d876f
      LOAD_BALANCER_ADDRESS: http://plugin-sales-api
      MONGO_URL: mongodb://erxes:UqKzqMhOOzFdNQhAzecLAiSk@erxes-dbs_mongo:27017/erxes?authSource=admin&replicaSet=rs0
      NODE_INSPECTOR: null
      ELASTIC_APM_HOST_NAME: null
      DEBUG: '*error*'
      NODE_ENV: production
      DOMAIN: https://test.erxes.io
      REDIS_HOST: erxes-dbs_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_pass
      ELASTICSEARCH_URL: http://erxes-dbs_elasticsearch:9200
      RELEASE: master
      VERSION: os
    extra_hosts: *default_hosts
    networks:
      - erxes
    deploy: *default_deploy

  plugin-content-api:
    image: erxes/erxes-next-content_api:latest
    environment:
      OTEL_SERVICE_NAME: content
      SERVICE_NAME: content
      PORT: 80
      CLIENT_PORTAL_DOMAINS: http://localhost:8080,http://localhost:7002,http://192.168.43.156:7002/
      JWT_TOKEN_SECRET: e0f3e51e3b0e026feb8eb53ba79d876f
      LOAD_BALANCER_ADDRESS: http://plugin-content-api
      MONGO_URL: mongodb://erxes:UqKzqMhOOzFdNQhAzecLAiSk@erxes-dbs_mongo:27017/erxes?authSource=admin&replicaSet=rs0
      NODE_INSPECTOR: null
      ELASTIC_APM_HOST_NAME: null
      DEBUG: '*error*'
      NODE_ENV: production
      DOMAIN: https://test.erxes.io
      REDIS_HOST: erxes-dbs_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_pass
      ELASTICSEARCH_URL: http://erxes-dbs_elasticsearch:9200
      RELEASE: master
      VERSION: os
    extra_hosts: *default_hosts
    networks:
      - erxes
    deploy: *default_deploy

  plugin-operation-api:
    image: erxes/erxes-next-operation_api:latest
    environment:
      OTEL_SERVICE_NAME: operation
      SERVICE_NAME: operation
      PORT: 80
      CLIENT_PORTAL_DOMAINS: http://localhost:8080,http://localhost:7002,http://192.168.43.156:7002/
      JWT_TOKEN_SECRET: e0f3e51e3b0e026feb8eb53ba79d876f
      LOAD_BALANCER_ADDRESS: http://plugin-operation-api
      MONGO_URL: mongodb://erxes:UqKzqMhOOzFdNQhAzecLAiSk@erxes-dbs_mongo:27017/erxes?authSource=admin&replicaSet=rs0
      NODE_INSPECTOR: null
      ELASTIC_APM_HOST_NAME: null
      DEBUG: '*error*'
      NODE_ENV: production
      DOMAIN: https://test.erxes.io
      REDIS_HOST: erxes-dbs_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_pass
      ELASTICSEARCH_URL: http://erxes-dbs_elasticsearch:9200
      RELEASE: master
      VERSION: os
    extra_hosts: *default_hosts
    networks:
      - erxes
    deploy: *default_deploy
  gateway:
    image: erxes/erxes-next-gateway:latest
    environment:
      OTEL_SERVICE_NAME: gateway
      SERVICE_NAME: gateway
      PORT: 80
      LOAD_BALANCER_ADDRESS: http://gateway
      JWT_TOKEN_SECRET: e0f3e51e3b0e026feb8eb53ba79d876f
      CLIENT_PORTAL_DOMAINS: http://localhost:8080,http://localhost:7002,http://192.168.43.156:7002/
      MONGO_URL: mongodb://erxes:UqKzqMhOOzFdNQhAzecLAiSk@erxes-dbs_mongo:27017/erxes?authSource=admin&replicaSet=rs0
      NODE_INSPECTOR: null
      ELASTIC_APM_HOST_NAME: null
      DEBUG: '*error*'
      NODE_ENV: production
      DOMAIN: https://test.erxes.io
      WIDGETS_DOMAIN: https://test.erxes.io/widgets
      REDIS_HOST: erxes-dbs_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_pass
      RABBITMQ_HOST: amqp://erxes:fAXkiGHctXpPHRyfOOjSxcaA@erxes-dbs_rabbitmq:5672/
      ELASTICSEARCH_URL: http://erxes-dbs_elasticsearch:9200
      RELEASE: master
      VERSION: os
      MESSAGE_BROKER_PREFIX: ''
      ALLOWED_ORIGINS: .*
      INTROSPECTION: 'true'
      ENABLED_PLUGINS: 'automations,logs,notifications,frontline,accounting,sales,operation'
    healthcheck:
      test: ['CMD', 'curl', '-i', 'http://localhost:80/health']
      interval: 30s
      start_period: 30s
    extra_hosts: *default_hosts
    ports:
      - 3300:80
    networks:
      - erxes
    deploy: *default_deploy
