export const ACTIVITY_MODULES = {
  NAME: 'NAME',
  STATUS: 'STATUS',
  LEAD: 'LEAD',
  PRIORITY: 'PRIORITY',
  TEAM: 'TEAM',
  START_DATE: 'START_DATE',
  END_DATE: 'END_DATE',
  ASSIGNEE: 'ASSIGNEE',
  ESTIMATE_POINT: 'ESTIMATE_POINT',
};

export const ACTIVITY_ACTIONS = {
  CREATED: 'CREATED',
  CHANGED: 'CHANGED',
  REMOVED: 'REMOVED',
} as const;
