import { ITransaction } from './types/Transaction';
import { IAccount } from '@/account/type/Account';

export const dummyTransactions: ITransaction[] = [
  {
    _id: '1',
    date: new Date('2023-10-01'),
    description: 'Monthly rent payment',
    status: 'approved',
    ptrId: 'ptr001',
    number: 'TR-001',
    journal: 'general',
    ptrStatus: 'completed',
    branchId: 'branch1',
    departmentId: 'dept1',
    customerType: 'company',
    customerId: 'cust001',
    assignedUserIds: ['user1', 'user2'],
    details: [
      {
        _id: 'detail1',
        accountId: 'acc001',
        side: 'debit',
        amount: 1000,
        account: {
          _id: 'acc001',
          name: 'Rent Expense',
          code: '1000',
          createdAt: new Date(),
          currency: 'USD',
          kind: 'expense',
          journal: 'general',
          status: 'active',
          isTemp: false,
          isOutBalance: false,
        } as IAccount,
      },
      {
        _id: 'detail2',
        accountId: 'acc002',
        side: 'credit',
        amount: 1000,
        account: {
          _id: 'acc002',
          name: 'Cash',
          code: '1001',
          createdAt: new Date(),
          currency: 'USD',
          kind: 'asset',
          journal: 'general',
          status: 'active',
          isTemp: false,
          isOutBalance: false,
        } as IAccount,
      },
    ],
    shortDetail: {
      _id: 'shortdetail1',
      accountId: 'acc001',
      side: 'debit',
      amount: 1000,
    },
    sumDt: 1000,
    sumCt: 1000,
  },
  {
    _id: '2',
    date: new Date('2023-10-05'),
    description: 'Office supplies purchase',
    status: 'pending',
    ptrId: 'ptr002',
    number: 'TR-002',
    journal: 'purchases',
    ptrStatus: 'pending',
    branchId: 'branch1',
    departmentId: 'dept2',
    customerType: 'vendor',
    customerId: 'vend001',
    details: [
      {
        _id: 'detail3',
        accountId: 'acc003',
        side: 'debit',
        amount: 500,
        account: {
          _id: 'acc003',
          name: 'Office Supplies',
          code: '1002',
          createdAt: new Date(),
          currency: 'USD',
          kind: 'expense',
          journal: 'purchases',
          status: 'active',
          isTemp: false,
          isOutBalance: false,
        } as IAccount,
      },
      {
        _id: 'detail4',
        accountId: 'acc002',
        side: 'credit',
        amount: 500,
        account: {
          _id: 'acc002',
          name: 'Cash',
          code: '1001',
          createdAt: new Date(),
          currency: 'USD',
          kind: 'asset',
          journal: 'general',
          status: 'active',
          isTemp: false,
          isOutBalance: false,
        } as IAccount,
      },
    ],
    shortDetail: {
      _id: 'shortdetail2',
      accountId: 'acc003',
      side: 'debit',
      amount: 500,
    },
    sumDt: 500,
    sumCt: 500,
  },
  {
    _id: '3',
    date: new Date('2023-10-10'),
    description: 'Employee salary payment',
    status: 'approved',
    ptrId: 'ptr003',
    number: 'TR-003',
    journal: 'payroll',
    ptrStatus: 'completed',
    branchId: 'branch2',
    departmentId: 'dept3',
    customerType: 'employee',
    customerId: 'emp001',
    hasVat: true,
    vatRowId: 'vat001',
    vatAmount: 150,
    details: [
      {
        _id: 'detail5',
        accountId: 'acc004',
        side: 'debit',
        amount: 1500,
        account: {
          _id: 'acc004',
          name: 'Salary Expense',
          code: '1003',
          createdAt: new Date(),
          currency: 'USD',
          kind: 'expense',
          journal: 'payroll',
          status: 'active',
          isTemp: false,
          isOutBalance: false,
        } as IAccount,
      },
      {
        _id: 'detail6',
        accountId: 'acc002',
        side: 'credit',
        amount: 1500,
        account: {
          _id: 'acc002',
          name: 'Cash',
          code: '1001',
          createdAt: new Date(),
          currency: 'USD',
          kind: 'asset',
          journal: 'general',
          status: 'active',
          isTemp: false,
          isOutBalance: false,
        } as IAccount,
      },
    ],
    shortDetail: {
      _id: 'shortdetail3',
      accountId: 'acc004',
      side: 'debit',
      amount: 1500,
    },
    sumDt: 1500,
    sumCt: 1500,
  },
];
